[package]
name = "vectordb-cli"
description = "A CLI tool for semantic code search."
version = "1.0.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]

[features]
default = ["onnx"]
onnx = []

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
indicatif = { version = "0.17.8", features = ["rayon"] }
walkdir = "2.3"
anyhow = "1.0.86"
thiserror = "1.0.61"
rayon = "1.7"
ndarray = "0.16"
tokenizers = { version = "0.21.1", features = ["http"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
serde_yaml = "0.9"
colored = "2.0"
dirs = "5.0.1"
tempfile = "3.5"
regex = "1.9.5"
rand = "0.8"
fastrand = "2.0"
num_cpus = "1.16.0"
log = "0.4.21"
chrono = { version = "0.4", features = ["serde"] }
# Code parsing dependencies
# tree-sitter = "0.20"
# tree-sitter-rust = "0.20"
# tree-sitter-ruby = "0.20"
# tree-sitter-go = "0.20"
# tree-sitter-javascript = "0.20"
# tree-sitter-typescript = "0.20"
# tree-sitter-yaml = "0.7.0"
lsp-types = "0.94"
crossbeam-channel = "0.5"
# Syntax parsing dependencies
# syn = { version = "2.0", features = ["full", "parsing", "extra-traits", "visit"] }
# proc-macro2 = "1.0"
# quote = "1.0"
ctrlc = "3.4"
# ONNX Runtime dependencies
ort = { version = "2.0.0-rc.9", features = ["cuda"] }
lru = "0.11.0"
lazy_static = "1.4.0"
# File watching dependency
notify = "6.1.1"
notify-debouncer-full = "0.3.1"
tokio = { version = "1.38.0", features = ["full"] }
tracing-subscriber = { version = "0.3", features = [ "env-filter", "fmt" ] }
bincode = "1.3"

[dev-dependencies]
tempfile = "3.6.0"
anyhow = "1.0"
# Add test-log dependency
test-log = "0.2"
assert_cmd = "2.0"
predicates = "3.1"

[[bin]]
name = "vectordb-cli"
path = "src/main.rs"

[[bin]]
name = "onnx_benchmark"
path = "src/bin/onnx_benchmark.rs"

[build-dependencies]
bindgen = "0.69.4"
