[package]
name = "vectordb-cli"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A lightweight CLI tool for semantic file search using vector embeddings"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
indicatif = "0.17"
walkdir = "2.3"
anyhow = "1.0"
thiserror = "1.0"
rayon = "1.7"
ndarray = "0.15"
tokenizers = { version = "0.15", features = ["http"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.0"
dirs = "5.0"
tempfile = "3.5"
regex = "1.8"
rand = "0.8"
num_cpus = "1.15"
# Code parsing dependencies
tree-sitter = "0.20"
tree-sitter-rust = "0.20"
tree-sitter-ruby = "0.20"
lsp-types = "0.94"
crossbeam-channel = "0.5"
# Syntax parsing dependencies
syn = { version = "2.0", features = ["full", "parsing", "extra-traits", "visit"] }
proc-macro2 = "1.0"
quote = "1.0"
ctrlc = "3.2"
# ONNX Runtime dependencies
ort = "1.16.0"

[dev-dependencies]
tempfile = "3.10"
