// src/grpc_generated/mod.rs
//! This module includes code generated by tonic-build.

// Only include the generated gRPC code if the "server" feature is enabled.
#[cfg(feature = "server")]
pub mod editing {
    // Attempt to make prost crate explicitly available to generated code
    extern crate prost;
    // Include the generated code from OUT_DIR. 
    // The filename corresponds to the package name in the proto file.
    tonic::include_proto!("editing"); 
}

// Include the generated descriptor set
#[cfg(feature = "server")]
include!(concat!(env!("OUT_DIR"), "/editing_descriptor.rs"));

// If the server feature is not enabled, the module remains empty.
#[cfg(not(feature = "server"))]
pub mod editing {} 

// If the server feature is not enabled, provide an empty descriptor
#[cfg(not(feature = "server"))]
pub const EDITING_FILE_DESCRIPTOR_SET: &[u8] = &[]; 